# Generated by Django 2.2.1 on 2019-05-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='price_small',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
