# Generated by Django 2.2.1 on 2019-05-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='Italy', max_length=64),
        ),
    ]
