# Generated by Django 2.2.1 on 2019-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190515_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='quote',
            field=models.CharField(default='Delicous', max_length=1000),
        ),
        migrations.AddField(
            model_name='pizza',
            name='url',
            field=models.CharField(default='https://img.buzzfeed.com/thumbnailer-prod-us-east-1/dc23cd051d2249a5903d25faf8eeee4c/BFV36537_CC2017_2IngredintDough4Ways-FB.jpg?output-quality=60&resize=1000:*', max_length=1000),
        ),
    ]
