# Generated by Django 2.2.1 on 2019-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pasta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='url',
            field=models.CharField(default='https://www.tasteofhome.com/wp-content/uploads/2017/10/Armenian-Garden-Salad_exps47594_TH2236620A05_31_3bC_RMS-1.jpg', max_length=1000),
        ),
    ]
