# Generated by Django 2.2.1 on 2019-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_salad_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platter',
            name='name',
            field=models.CharField(default='Garden Salad', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='url',
            field=models.CharField(default='/static/orders/images/pasta-1.jpg', max_length=1000),
        ),
    ]
