# Generated by Django 2.2.1 on 2019-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190603_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner_platter',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='carts',
        ),
        migrations.AddField(
            model_name='cart',
            name='dinner_platters',
            field=models.ManyToManyField(to='orders.Dinner_Platter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pastas',
            field=models.ManyToManyField(to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pizzas',
            field=models.ManyToManyField(to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='cart',
            name='salads',
            field=models.ManyToManyField(to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='cart',
            name='subs',
            field=models.ManyToManyField(to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
