# Generated by Django 2.2.2 on 2019-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190603_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
